"""Initial migration

Revision ID: ffe97b4a6115
Revises: 
Create Date: 2025-11-08 07:39:33.922195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe97b4a6115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_logs')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('idx_priority', ['priority'], unique=False)
        batch_op.create_index('idx_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('idx_status')
        batch_op.drop_index('idx_start_date')
        batch_op.drop_index('idx_priority')

    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=False),
    sa.Column('update_text', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
